"""Add user daily_minutes_used

Revision ID: 3087aeb6376a
Revises: ea1fb07f50e8
Create Date: 2026-06-25 10:24:24.923785

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3087aeb6376a"
down_revision: str | None = "ea1fb07f50e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "daily_minutes_used", sa.Float(), server_default="0.0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "daily_minutes_used")
    # ### end Alembic commands ###
