"""add email_verification_token to users

Revision ID: 4c6359c656f5
Revises: eb479db95f34
Create Date: 2026-06-26 00:20:56.736264

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c6359c656f5"
down_revision: str | None = "eb479db95f34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email_verification_token", sa.String(length=255), nullable=True),
    )
    op.create_unique_constraint(None, "users", ["email_verification_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "email_verification_token")
    # ### end Alembic commands ###
