"""create_video_pipeline_tables_and_constraints

Revision ID: 79b85294de0a
Revises: 48231c1eca00
Create Date: 2026-07-04 11:08:07.966809

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79b85294de0a"
down_revision: str | None = "48231c1eca00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("video_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(), nullable=True),
        sa.Column("timeout_at", sa.DateTime(), nullable=True),
        sa.Column("locked_by", sa.String(length=64), nullable=True),
        sa.Column("celery_task_id", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_job_queue_status", "job_queue", ["status"], unique=False)
    op.create_index(
        "idx_job_queue_video_status", "job_queue", ["video_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_job_queue_celery_task_id"),
        "job_queue",
        ["celery_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_queue_job_type"), "job_queue", ["job_type"], unique=False
    )
    op.create_index(
        op.f("ix_job_queue_locked_by"), "job_queue", ["locked_by"], unique=False
    )
    op.create_index(
        op.f("ix_job_queue_video_id"), "job_queue", ["video_id"], unique=False
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("source_language", sa.String(length=10), nullable=True),
        sa.Column("target_language", sa.String(length=10), nullable=False),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("current_step", sa.Text(), nullable=True),
        sa.Column("step_detail", sa.Text(), nullable=True),
        sa.Column("total_segments", sa.Integer(), nullable=False),
        sa.Column("processed_segments", sa.Integer(), nullable=False),
        sa.Column("current_segment_index", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("total_batches", sa.Integer(), nullable=False),
        sa.Column("processed_batches", sa.Integer(), nullable=False),
        sa.Column("style_guide", sa.Text(), nullable=True),
        sa.Column("context_analysis", sa.Text(), nullable=True),
        sa.Column("skip_glossary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "processing_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("step", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "segments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("translated_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_segments_video_seq",
        "segments",
        ["video_id", "sequence_number"],
        unique=False,
    )
    op.create_table(
        "terms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("original_term", sa.Text(), nullable=False),
        sa.Column("translated_term", sa.Text(), nullable=False),
        sa.Column("is_standardized", sa.Boolean(), nullable=False),
        sa.Column("standardized_term", sa.Text(), nullable=True),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "term_occurrences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("term_id", sa.String(length=36), nullable=False),
        sa.Column("segment_id", sa.String(length=36), nullable=False),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["segment_id"], ["segments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["term_id"], ["terms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "translation_variants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("term_id", sa.String(length=36), nullable=False),
        sa.Column("variant_translation", sa.Text(), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("segment_ids", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["term_id"], ["terms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_users_api_key_mode", "users", type_="check")
    op.drop_table("translation_variants")
    op.drop_table("term_occurrences")
    op.drop_table("terms")
    op.drop_index("idx_segments_video_seq", table_name="segments")
    op.drop_table("segments")
    op.drop_table("processing_logs")
    op.drop_table("videos")
    op.drop_index(op.f("ix_job_queue_video_id"), table_name="job_queue")
    op.drop_index(op.f("ix_job_queue_locked_by"), table_name="job_queue")
    op.drop_index(op.f("ix_job_queue_job_type"), table_name="job_queue")
    op.drop_index(op.f("ix_job_queue_celery_task_id"), table_name="job_queue")
    op.drop_index("idx_job_queue_video_status", table_name="job_queue")
    op.drop_index("idx_job_queue_status", table_name="job_queue")
    op.drop_table("job_queue")
    # ### end Alembic commands ###
