"""add email verification token expiry

Revision ID: 89f9ff1767d4
Revises: f23766cae521
Create Date: 2026-06-26 01:35:21.889689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f9ff1767d4'
down_revision: Union[str, None] = 'f23766cae521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_token_expires_at')
    # ### end Alembic commands ###
