"""add email verification token expiry

Revision ID: 89f9ff1767d4
Revises: f23766cae521
Create Date: 2026-06-26 01:35:21.889689

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89f9ff1767d4"
down_revision: str | None = "f23766cae521"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email_verification_token_expires_at", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verification_token_expires_at")
    # ### end Alembic commands ###
