"""add users and analytics tables

Revision ID: 92302a4839eb
Revises: 
Create Date: 2026-06-24 09:46:31.297245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '92302a4839eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)

    # ### commands auto generated by Alembic - please adjust! ###
    if not inspector.has_table('users'):
        op.create_table('users',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('password_hash', sa.String(length=255), nullable=False),
            sa.Column('is_email_verified', sa.Boolean(), nullable=False),
            sa.Column('wants_updates', sa.Boolean(), nullable=False),
            sa.Column('daily_upload_mb_used', sa.Float(), nullable=False),
            sa.Column('daily_videos_used', sa.Integer(), nullable=False),
            sa.Column('quota_reset_at', sa.DateTime(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('email')
        )
        op.create_index('idx_users_email', 'users', ['email'], unique=True)
        op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)

    if not inspector.has_table('user_sessions'):
        op.create_table('user_sessions',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('user_id', sa.String(length=36), nullable=False),
            sa.Column('token', sa.String(length=255), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('token')
        )
        op.create_index('idx_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
        op.create_index('idx_user_sessions_token', 'user_sessions', ['token'], unique=True)
        op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)

    if not inspector.has_table('page_views'):
        op.create_table('page_views',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('user_id', sa.String(length=36), nullable=True),
            sa.Column('path', sa.String(length=2048), nullable=False),
            sa.Column('session_id', sa.String(length=255), nullable=True),
            sa.Column('ip_hash', sa.String(length=128), nullable=True),
            sa.Column('user_agent', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_page_views_created_at', 'page_views', ['created_at'], unique=False)
        op.create_index('idx_page_views_path', 'page_views', ['path'], unique=False)
        op.create_index('idx_page_views_session_id', 'page_views', ['session_id'], unique=False)
        op.create_index('idx_page_views_user_id', 'page_views', ['user_id'], unique=False)

    if not inspector.has_table('usage_events'):
        op.create_table('usage_events',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('user_id', sa.String(length=36), nullable=True),
            sa.Column('event_type', sa.String(length=128), nullable=False),
            sa.Column('metadata', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_usage_events_created_at', 'usage_events', ['created_at'], unique=False)
        op.create_index('idx_usage_events_event_type', 'usage_events', ['event_type'], unique=False)
        op.create_index('idx_usage_events_user_id', 'usage_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_events')
    op.drop_table('page_views')
    op.drop_table('user_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
