"""add password reset token to users

Revision ID: 97403f57fa23
Revises: 9ad471102ff0
Create Date: 2026-06-28 19:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97403f57fa23"
down_revision: str | None = "9ad471102ff0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password_reset_token", sa.String(length=255), nullable=True),
    )
    op.create_unique_constraint(None, "users", ["password_reset_token"])
    op.add_column(
        "users",
        sa.Column(
            "password_reset_token_expires_at", sa.DateTime(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_reset_token_expires_at")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "password_reset_token")
    # ### end Alembic commands ###
