"""add profile fields to users

Revision ID: 9ad471102ff0
Revises: 9a5eeeeb9d7d
Create Date: 2026-06-28 18:30:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ad471102ff0"
down_revision: str | None = "9a5eeeeb9d7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("display_name", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "total_minutes_used", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column("sessions_invalidated_at", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sessions_invalidated_at")
    op.drop_column("users", "total_minutes_used")
    op.drop_column("users", "display_name")
    # ### end Alembic commands ###
