"""Add newsletter signups and user api_key_mode

Revision ID: ea1fb07f50e8
Revises: 92302a4839eb
Create Date: 2026-06-25 10:10:35.177923

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea1fb07f50e8"
down_revision: str | None = "92302a4839eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletter_signups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_newsletter_signups_email"),
        "newsletter_signups",
        ["email"],
        unique=True,
    )
    op.add_column(
        "users",
        sa.Column(
            "api_key_mode",
            sa.String(length=50),
            server_default="standard",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "api_key_mode")
    op.drop_index(op.f("ix_newsletter_signups_email"), table_name="newsletter_signups")
    op.drop_table("newsletter_signups")
    # ### end Alembic commands ###
