"""add_user_id_to_videos

Revision ID: f23766cae521
Revises: 4c6359c656f5
Create Date: 2026-06-26 00:54:42.764266

"""
import logging
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision: str = 'f23766cae521'
down_revision: Union[str, None] = '4c6359c656f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)

    if not inspector.has_table('videos'):
        logger.info("Table 'videos' does not exist yet; skipping user_id migration.")
        return

    columns = {col["name"] for col in inspector.get_columns('videos')}
    if 'user_id' in columns:
        logger.info("Column 'user_id' already exists on 'videos'; skipping.")
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'videos', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)

    if not inspector.has_table('videos'):
        return

    columns = {col["name"] for col in inspector.get_columns('videos')}
    if 'user_id' not in columns:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'user_id')
    # ### end Alembic commands ###
